In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [39]:
df = pd.read_csv("D:\Pythoon for DataSCIENCES\Machine learning\WA_Fn-UseC_-Telco-Customer-Churn.csv")

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\deppa\AppData\Local\Temp\ipykernel_21480\3676741945.py:1: SyntaxWarning: invalid escape sequence '\P'
  df = pd.read_csv("D:\Pythoon for DataSCIENCES\Machine learning\WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [40]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [42]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [43]:
df.TotalCharges = pd.to_numeric(df.TotalCharges,errors='coerce')

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [45]:
df.dropna(how='any',inplace=True)

In [46]:
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [47]:
x = df.drop(['customerID','Churn'],axis=1)

In [48]:
y = df.Churn.values

In [49]:
x

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50

In [50]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y = encoder.fit_transform(y)

print(y)  # Output: [1 0 1 0]

[0 0 1 ... 0 1 0]

In [51]:
y

array([0, 0, 1, ..., 0, 1, 0])

In [52]:
x.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='object')

In [53]:
x = pd.get_dummies(x,columns=['gender', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       ] ,drop_first=True,dtype='int')

In [54]:
x

,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,tenure_2,tenure_3,tenure_4,tenure_5,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,29.85,29.85,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
1,0,56.95,1889.50,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
2,0,53.85,108.15,1,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,1
3,0,42.30,1840.75,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,0,70.70,151.65,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,84.80,1990.50,1,1,1,0,0,0,0,...,0,1,0,1,1,0,1,0,0,1
7039,0,103.20,7362.90,0,1,1,0,0,0,0,...,0,1,0,1,1,0,1,1,0,0
7040,0,29.60,346.45,0,1,1,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
7041,1,74.40,306.60,1,1,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
7042,0,105.65,6844.50,1,0,0,0,0,0,0,...,0,1,0,1,0,1,1,0,0,0

In [55]:
# splititng data into train test split

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y ,test_size=0.25,random_state=42)

In [56]:
len(x_train)

5274

In [57]:
len(x_test)

1758

In [58]:
# Feature Scailing
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

In [59]:
x_train_sc = sc.fit_transform(x_train)
x_test_sc = sc.transform(x_test)

In [60]:
x_train_sc

array([[-0.4377158 , -0.52638   , -0.71215437, ..., -0.53100285,
        -0.71708569, -0.54360352],
       [-0.4377158 ,  0.85826225,  0.29030505, ...,  1.88322907,
        -0.71708569, -0.54360352],
       [-0.4377158 ,  1.41543565,  1.25906669, ..., -0.53100285,
        -0.71708569, -0.54360352],
       ...,
       [-0.4377158 ,  0.54651046, -0.65903002, ..., -0.53100285,
         1.39453348, -0.54360352],
       [-0.4377158 , -1.48982568, -0.56849072, ..., -0.53100285,
        -0.71708569, -0.54360352],
       [ 2.28458741,  0.29777233, -0.35853779, ..., -0.53100285,
         1.39453348, -0.54360352]])

In [61]:
x.head()

,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,tenure_2,tenure_3,tenure_4,tenure_5,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,29.85,29.85,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
1,0,56.95,1889.50,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
2,0,53.85,108.15,1,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,1
3,0,42.30,1840.75,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,0,70.70,151.65,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,1,0

## KNN Classifier

In [62]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=5)

model.fit(x_train_sc,y_train)


y_pred = model.predict(x_test_sc)


# check accuracy
from sklearn.metrics import accuracy_score,recall_score,confusion_matrix

accuracy_score(y_pred ,y_test)*100

76.79180887372013

In [63]:
confusion_matrix(y_pred,y_test)

array([[1119,  227],
       [ 181,  231]], dtype=int64)

In [64]:
from sklearn.metrics import recall_score,precision_recall_curve,classification_report

In [65]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.86      0.83      0.85      1346
           1       0.50      0.56      0.53       412

    accuracy                           0.77      1758
   macro avg       0.68      0.70      0.69      1758
weighted avg       0.78      0.77      0.77      1758

In [66]:
from sklearn.metrics import roc_auc_score

print(roc_auc_score(y_pred,y_test))

0.6960158830912158

In [68]:

print(recall_score(y_pred,y_test))

print(precision_recall_curve(y_pred,y_test))

0.5606796116504854
(array([0.23435722, 0.50436681, 1.        ]), array([1.        , 0.56067961, 0.        ]), array([0, 1]))

# Naive Bayes Classifier

In [70]:
from sklearn.naive_bayes import  GaussianNB

GD = GaussianNB()

GD.fit(x_train_sc,y_train)


y_pred = GD.predict(x_test_sc)


# check accuracy
from sklearn.metrics import accuracy_score,recall_score,confusion_matrix

accuracy_score(y_pred ,y_test)*100

68.48691695108077

# SVM

In [ ]:
from sklearn.svm import SVC

model_svc =SVC()

model_svc.fit(x_train_sc,y_train)


y_pred = model_svc.predict(x_test_sc)


# check accuracy
from sklearn.metrics import accuracy_score,recall_score,confusion_matrix

accuracy_score(y_pred ,y_test)*100

78.66894197952219

# Logistic Regression

In [73]:
from sklearn.linear_model import LogisticRegression

model_lr =LogisticRegression( )

model_lr.fit(x_train_sc,y_train)


y_pred_lr = model_lr.predict(x_test_sc)


# check accuracy
from sklearn.metrics import accuracy_score,recall_score,confusion_matrix

accuracy_score(y_pred_lr ,y_test)*100

78.10011376564277

# Random Forest

In [76]:
from sklearn.ensemble import RandomForestClassifier

model_rf =RandomForestClassifier(n_estimators=10,max_depth=5 )

model_rf.fit(x_train_sc,y_train)


y_pred_rf = model_rf.predict(x_test_sc)


# check accuracy
from sklearn.metrics import accuracy_score,recall_score,confusion_matrix

accuracy_score(y_pred_rf ,y_test)*100

78.04323094425484

# Decision Tree

In [85]:
from sklearn.tree import DecisionTreeClassifier

model_dc =DecisionTreeClassifier(criterion='entropy',splitter='random',max_features=10,max_depth=5)

model_dc.fit(x_train_sc,y_train)


y_pred_dc = model_dc.predict(x_test_sc)


# check accuracy
from sklearn.metrics import accuracy_score,recall_score,confusion_matrix

accuracy_score(y_pred_dc ,y_test)*100

75.36973833902162