## Ridge And Lasso Regularization

In [106]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
# from sklearn.datasets import load_boston

In [107]:
from sklearn.datasets import fetch_openml

boston = fetch_openml(name="boston", version=1, as_frame=True)
df = pd.DataFrame(boston.data, columns=boston.feature_names)
df['Price'] = boston.target

In [108]:
df

        CRIM    ZN  INDUS CHAS    NOX  ...    TAX  PTRATIO       B LSTAT  Price
0    0.00632  18.0   2.31    0  0.538  ...  296.0     15.3  396.90  4.98   24.0
1    0.02731   0.0   7.07    0  0.469  ...  242.0     17.8  396.90  9.14   21.6
2    0.02729   0.0   7.07    0  0.469  ...  242.0     17.8  392.83  4.03   34.7
3    0.03237   0.0   2.18    0  0.458  ...  222.0     18.7  394.63  2.94   33.4
4    0.06905   0.0   2.18    0  0.458  ...  222.0     18.7  396.90  5.33   36.2
..       ...   ...    ...  ...    ...  ...    ...      ...     ...   ...    ...
501  0.06263   0.0  11.93    0  0.573  ...  273.0     21.0  391.99  9.67   22.4
502  0.04527   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  9.08   20.6
503  0.06076   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  5.64   23.9
504  0.10959   0.0  11.93    0  0.573  ...  273.0     21.0  393.45  6.48   22.0
505  0.04741   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  7.88   11.9

[506 rows x 14 columns]

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    category
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    category
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  Price    506 non-null    float64
dtypes: category(2), float64(12)
memory usage: 49.0 KB

In [110]:
X = df.drop('Price', axis=1)
y = df['Price']

In [111]:
X

        CRIM    ZN  INDUS CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0    0.00632  18.0   2.31    0  0.538  ...    1  296.0     15.3  396.90   4.98
1    0.02731   0.0   7.07    0  0.469  ...    2  242.0     17.8  396.90   9.14
2    0.02729   0.0   7.07    0  0.469  ...    2  242.0     17.8  392.83   4.03
3    0.03237   0.0   2.18    0  0.458  ...    3  222.0     18.7  394.63   2.94
4    0.06905   0.0   2.18    0  0.458  ...    3  222.0     18.7  396.90   5.33
..       ...   ...    ...  ...    ...  ...  ...    ...      ...     ...    ...
501  0.06263   0.0  11.93    0  0.573  ...    1  273.0     21.0  391.99   9.67
502  0.04527   0.0  11.93    0  0.573  ...    1  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93    0  0.573  ...    1  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93    0  0.573  ...    1  273.0     21.0  393.45   6.48
505  0.04741   0.0  11.93    0  0.573  ...    1  273.0     21.0  396.90   7.88

[506 rows x 13 columns]

In [112]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: Price, Length: 506, dtype: float64

In [113]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [114]:
print(type(X_train))
print(type(X_test))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

In [115]:
cat_cols = ['CHAS', 'RAD']
X_train = pd.get_dummies(X_train, columns=cat_cols, drop_first=True)
X_test  = pd.get_dummies(X_test,  columns=cat_cols, drop_first=True)
X_train.astype('float64')
X_test.astype('float64')

         CRIM    ZN  INDUS    NOX     RM  ...  RAD_4  RAD_5  RAD_6  RAD_7  RAD_8
173   0.09178   0.0   4.05  0.510  6.416  ...    0.0    1.0    0.0    0.0    0.0
274   0.05644  40.0   6.41  0.447  6.758  ...    1.0    0.0    0.0    0.0    0.0
491   0.10574   0.0  27.74  0.609  5.983  ...    1.0    0.0    0.0    0.0    0.0
72    0.09164   0.0  10.81  0.413  6.065  ...    1.0    0.0    0.0    0.0    0.0
452   5.09017   0.0  18.10  0.713  6.297  ...    0.0    0.0    0.0    0.0    0.0
..        ...   ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
412  18.81100   0.0  18.10  0.597  4.628  ...    0.0    0.0    0.0    0.0    0.0
436  14.42080   0.0  18.10  0.740  6.461  ...    0.0    0.0    0.0    0.0    0.0
411  14.05070   0.0  18.10  0.597  6.657  ...    0.0    0.0    0.0    0.0    0.0
86    0.05188   0.0   4.49  0.449  6.015  ...    0.0    0.0    0.0    0.0    0.0
75    0.09512   0.0  12.83  0.437  6.286  ...    0.0    1.0    0.0    0.0    0.0

[102 rows x 20 columns]

In [116]:
print(X_test.dtypes)

CRIM       float64
ZN         float64
INDUS      float64
NOX        float64
RM         float64
AGE        float64
DIS        float64
TAX        float64
PTRATIO    float64
B          float64
LSTAT      float64
CHAS_1        bool
RAD_2         bool
RAD_24        bool
RAD_3         bool
RAD_4         bool
RAD_5         bool
RAD_6         bool
RAD_7         bool
RAD_8         bool
dtype: object

In [117]:
print(len(X_train), len(X_test))

404 102

In [118]:
df.corr()

             CRIM        ZN     INDUS  ...         B     LSTAT     Price
CRIM     1.000000 -0.200469  0.406583  ... -0.385064  0.455621 -0.388305
ZN      -0.200469  1.000000 -0.533828  ...  0.175520 -0.412995  0.360445
INDUS    0.406583 -0.533828  1.000000  ... -0.356977  0.603800 -0.483725
CHAS    -0.055892 -0.042697  0.062938  ...  0.048788 -0.053929  0.175260
NOX      0.420972 -0.516604  0.763651  ... -0.380051  0.590879 -0.427321
RM      -0.219247  0.311991 -0.391676  ...  0.128069 -0.613808  0.695360
AGE      0.352734 -0.569537  0.644779  ... -0.273534  0.602339 -0.376955
DIS     -0.379670  0.664408 -0.708027  ...  0.291512 -0.496996  0.249929
RAD      0.625505 -0.311948  0.595129  ... -0.444413  0.488676 -0.381626
TAX      0.582764 -0.314563  0.720760  ... -0.441808  0.543993 -0.468536
PTRATIO  0.289946 -0.391679  0.383248  ... -0.177383  0.374044 -0.507787
B       -0.385064  0.175520 -0.356977  ...  1.000000 -0.366087  0.333461
LSTAT    0.455621 -0.412995  0.603800  ... -0.366087  1.000000 -0.737663
Price   -0.388305  0.360445 -0.483725  ...  0.333461 -0.737663  1.000000

[14 rows x 14 columns]

#### Linear Regression

In [119]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [120]:
y_pred = model.predict(X_test)
r2_model = r2_score(y_test, y_pred)
print("R-squared score model:", r2_model)

R-squared score model: 0.6615687658684883

#### Ridge Regularization

In [121]:
from sklearn.linear_model import Ridge, Lasso

In [122]:
# manual hyperparameter tuning for Ridge regression in alpha values
ridge_model = Ridge(alpha=1.0)

ridge_model.fit(X_train, y_train)
ridge_pred = ridge_model.predict(X_test)
r2_ridge = r2_score(y_test, ridge_pred) 
print("R-squared score Ridge:", r2_ridge)

R-squared score Ridge: 0.6573061959309033

In [123]:
ridge_model = Ridge(alpha=0.2) # change alpha to see the effect of regularization
ridge_model.fit(X_train, y_train)
ridge_pred = ridge_model.predict(X_test)
r2_ridge = r2_score(y_test, ridge_pred) 
print("R-squared score Ridge:", r2_ridge)

R-squared score Ridge: 0.6611036234991843

In [124]:
ridge_model = Ridge(alpha=0.7) # change alpha to see the effect of regularization
ridge_model.fit(X_train, y_train)
ridge_pred = ridge_model.predict(X_test)
r2_ridge = r2_score(y_test, ridge_pred) 
print("R-squared score Ridge:", r2_ridge)

R-squared score Ridge: 0.6587324121998228

In [125]:
ridge_model = Ridge(alpha=0.1) # change alpha to see the effect of regularization
ridge_model.fit(X_train, y_train)
ridge_pred = ridge_model.predict(X_test)
r2_ridge = r2_score(y_test, ridge_pred) 
print("R-squared score Ridge:", r2_ridge)

R-squared score Ridge: 0.6614186605143559

#### Lasso Regularization

In [126]:
lasso_model = Lasso(alpha=0.1) # change alpha to see the effect of regularization
lasso_model.fit(X_train, y_train)
lasso_pred = lasso_model.predict(X_test)
r2_lasso = r2_score(y_test, lasso_pred)
print("R-squared score Lasso:", r2_lasso)

R-squared score Lasso: 0.6318702984163735

In [127]:
lasso_model = Lasso(alpha=1.0) # change alpha to see the effect of regularization
lasso_model.fit(X_train, y_train)
lasso_pred = lasso_model.predict(X_test)
r2_lasso = r2_score(y_test, lasso_pred)
print("R-squared score Lasso:", r2_lasso)

R-squared score Lasso: 0.6394368766139396

In [128]:
lasso_model = Lasso(alpha=0.5) # change alpha to see the effect of regularization
lasso_model.fit(X_train, y_train)
lasso_pred = lasso_model.predict(X_test)
r2_lasso = r2_score(y_test, lasso_pred)
print("R-squared score Lasso:", r2_lasso)

R-squared score Lasso: 0.6418902460508582

In [129]:
lasso_model = Lasso(alpha=0.7) # change alpha to see the effect of regularization
lasso_model.fit(X_train, y_train)
lasso_pred = lasso_model.predict(X_test)
r2_lasso = r2_score(y_test, lasso_pred)
print("R-squared score Lasso:", r2_lasso)

R-squared score Lasso: 0.6434689716273638

In [130]:
df.head(5)

      CRIM    ZN  INDUS CHAS    NOX  ...    TAX  PTRATIO       B LSTAT  Price
0  0.00632  18.0   2.31    0  0.538  ...  296.0     15.3  396.90  4.98   24.0
1  0.02731   0.0   7.07    0  0.469  ...  242.0     17.8  396.90  9.14   21.6
2  0.02729   0.0   7.07    0  0.469  ...  242.0     17.8  392.83  4.03   34.7
3  0.03237   0.0   2.18    0  0.458  ...  222.0     18.7  394.63  2.94   33.4
4  0.06905   0.0   2.18    0  0.458  ...  222.0     18.7  396.90  5.33   36.2

[5 rows x 14 columns]

In [131]:
X_train.columns[bad_feature]

Index(['NOX', 'CHAS_1', 'RAD_2', 'RAD_24', 'RAD_3', 'RAD_4', 'RAD_5', 'RAD_6',
       'RAD_7', 'RAD_8'],
      dtype='object')

In [132]:
# identify the coefficient with bad slope results in Lasso regression
bad_feature = np.where(lasso_model.coef_ == 0)[0]
print("Features with zero coefficients in Lasso regression:", X_train.columns[bad_feature].tolist())

Features with zero coefficients in Lasso regression: ['NOX', 'CHAS_1', 'RAD_2', 'RAD_24', 'RAD_3', 'RAD_4', 'RAD_5', 'RAD_6', 'RAD_7', 'RAD_8']

In [133]:
# drop the features with zero coefficients in Lasso regression and re-evaluate the model performance
x_train_filtered = X_train.drop(X_train.columns[bad_feature], axis=1)
x_test_filtered = X_test.drop(X_test.columns[bad_feature], axis=1)

#apply the  linear and lasso regression again with the filtered features
linear_model_filtered = LinearRegression()
linear_model_filtered.fit(x_train_filtered, y_train)

lasso_model_filtered = Lasso(alpha=0.5) # change alpha to see the effect of regularization
lasso_model_filtered.fit(x_train_filtered, y_train)

# Evaluate the models on the filtered data
y_pred_linear_filtered = linear_model_filtered.predict(x_test_filtered)
y_pred_lasso_filtered = lasso_model_filtered.predict(x_test_filtered)

# Calculate R-squared scores for the filtered models
r2_lr = r2_score(y_test, y_pred_linear_filtered)
r2_lasso = r2_score(y_test, y_pred_lasso_filtered)


print("Linear Regression (filtered features) - R2:", r2_lr)
print("Lasso Regression (filtered features) - R2:", r2_lasso)

Linear Regression (filtered features) - R2: 0.6219303471360468
Lasso Regression (filtered features) - R2: 0.6418959183037014

In [134]:
# The above code demonstrates how to apply Ridge and Lasso regression to the Boston housing dataset, and how changing the alpha parameter affects the R-squared score of the models. It also identifies which features have zero coefficients in the Lasso regression, and then re-evaluates the performance of both Linear and Lasso regression after dropping those features.

In [135]:
# identify the coefficicent with value closer to zero 

small_coefficients = np.where((lasso_model.coef_ <0.5) & (lasso_model.coef_ >-0.5))  [0]

In [136]:
small_coefficients

array([ 0,  1,  2,  3,  5,  7,  9, 11, 12, 13, 14, 15, 16, 17, 18, 19],
      dtype=int64)

In [137]:
print('Feature with small coefficients in Lasso regression:', X_train.columns[small_coefficients].tolist())

Feature with small coefficients in Lasso regression: ['CRIM', 'ZN', 'INDUS', 'NOX', 'AGE', 'TAX', 'B', 'CHAS_1', 'RAD_2', 'RAD_24', 'RAD_3', 'RAD_4', 'RAD_5', 'RAD_6', 'RAD_7', 'RAD_8']

In [138]:
df.head(5)

      CRIM    ZN  INDUS CHAS    NOX  ...    TAX  PTRATIO       B LSTAT  Price
0  0.00632  18.0   2.31    0  0.538  ...  296.0     15.3  396.90  4.98   24.0
1  0.02731   0.0   7.07    0  0.469  ...  242.0     17.8  396.90  9.14   21.6
2  0.02729   0.0   7.07    0  0.469  ...  242.0     17.8  392.83  4.03   34.7
3  0.03237   0.0   2.18    0  0.458  ...  222.0     18.7  394.63  2.94   33.4
4  0.06905   0.0   2.18    0  0.458  ...  222.0     18.7  396.90  5.33   36.2

[5 rows x 14 columns]